name: Automaticky make

on:
  push:
    branches:
      - master

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2
      - name: get the sha
        run: |-
          echo "$GITHUB_CONTEXT"| jq '.event.commits[].id' | tail -2 | head -1 |sed 's/\"//g'
          echo "$GITHUB_CONTEXT"| jq '.event.commits[].id' | tail -3 | head -1 |sed 's/\"//g'
          echo "$GITHUB_CONTEXT"| jq '.event.after'
          echo "$GITHUB_CONTEXT"| jq '.event.before'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Install Pandoc
        run: sudo apt-get install pandoc
      - name: Install Make
        run: sudo apt-get install make
      - name: Test of installing LaTeX
        run: sudo apt install texlive-latex-extra
      - name: Run Makefile and check git status
        run: make all
      - name: Push
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          if ! git diff --quiet; then
            echo "There are changes"
            git add -A
            timestamp=$(date -u)
            git commit -m "Vygenerovany file ve složce: ${timestamp}" || exit 0
            git push
          else
            echo "There are no changes, not pushing anything"
          fi
