name: Automaticky make

on:
  push:
    branches:
      - master

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      #- name: Checks pandoc version
      #  uses: docker://pandoc/core:2.9
      #  with:
      #    args: "--version"
      - name: Install Pandoc
        run: sudo apt-get install pandoc
      - name: Install Make
        run: sudo apt-get install make
      - name: Test of installing LaTeX
        run: sudo apt install texlive-latex-extra
      - name: Check current working directory
        run: |-
          git clone https://github.com/Dominik-97/Magisterske_Studium.git
      - name: Run Makefile and check git status
        run: |-
          cd Magisterske_Studium/
          make all
      - name: Push
        run: |-
          git config --global user.name "Automated Push"
          git config --global user.email "myniceemail@greatdomain.com"
          #git status
          git add -A
          timestamp=$(date -u)
          git commit -m "Vygenerovany file ve složce: ${timestamp}" || exit 0
          git push #-u origin master
