name: Automaticky make

on:
  push:
    branches:
      - master

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2
      - name: Install Pandoc
        run: |-
          last_push=$(git rev-parse origin/@)
          lastlast_push=$(git rev-parse origin/@~)
          echo $last_push
          echo $lastlast_push
          if ! git diff --quiet $last_push $lastlast_push; then
            echo "There are changes, installing pandoc"
            #sudo apt-get install pandoc
          else
            echo "There are no changes, not installing pandoc"
          fi
      - name: Install Make
        run: |-
          if ! git diff --quiet; then
            echo "There are changes, installing make"
            sudo apt-get install make
          else
            echo "There are no changes, not installing make"
          fi
      - name: Test of installing LaTeX
        run: |-
          if ! git diff --quiet; then
            echo "There are changes, installing latex"
            sudo apt install texlive-latex-extra
          else
            echo "There are no changes, not installing latex"
          fi
      - name: Run Makefile and check git status
        run: |-
          if ! git diff --quiet; then
            echo "There are changes, executing make"
            make all
          else
            echo "There are no changes, not executing make"
          fi
      - name: Push
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          if ! git diff --quiet; then
            echo "There are changes"
            git add -A
            timestamp=$(date -u)
            git commit -m "Vygenerovany file ve složce: ${timestamp}" || exit 0
            git push
          else
            echo "There are no changes"
          fi
