name: Automaticky make

on:
  push:
    branches:
      - master

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2
      - name: Cleaning
        run: sudo apt-get clean
      - name: Updating
        run: sudo apt-get update
      - name: Install Pandoc
        run: sudo apt-get install pandoc
      - name: Install Make
        run: sudo apt-get install make
      - name: Install texlive-lang-czechslovak
        run: sudo apt-get install texlive-lang-czechslovak
      - name: Test of installing LaTeX
        run: sudo apt install texlive-latex-extra
      - name: Install NPM
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install NPM package
        run: npm i -g mermaid-filter
      - name: Run Makefile and check git status
        run: make all
      - name: Push
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Vygenerovany file ve složce: ${timestamp}" || exit 0
          git push
